### PR TITLE
add command line option for oncokb annotation

### PR DESCRIPTION
**Pull request by rjcorb**
### Purpose/implementation Section

Update `09-lollipop` analysis module so that OncoKB access token is provided in command line when running analysis module. 

#### What scientific question is your analysis addressing?

NA

#### What was your approach?

- Divided the analysis module into three scripts: 
 1. 01-create-maf-subset.Rmd subsets MAF for oncokb annotation2. 
 2. 02-run-oncokb-annotation.sh runs MafAnnotator.py from oncokb_annotator GitHub repo3. 
 3. 03-create-lollipop.Rmd generates lollipop plots 4. 

- Set variable ONCOKB to be defined with Oncokb access token when running `run_lollipop.sh` shell script. 
- Created README file with instructions on defining access token variable when running module. 

#### What GitHub issue does your pull request address?

[Ticket #59](https://github.com/d3b-center/PBTA-ALT-analysis/issues/59)

#### Which areas should receive a particularly close look?

- confirm that module runs with personal Oncokb access token
- confirm changes in plot `atria-lollipop-comp.tiff` is as expected 

#### Is there anything that you want to discuss further?

No

#### What types of results are included (e.g., table, figure)?

MAF subset tables:
`hgat-goi.maf.tsv`
`snv-dgd-goi.maf.tsv`

OncoKB annotation results: 
`dgd_maf-goi-oncokb.tsv`
`snv-consensus-plus-hotspots-hgat-oncokb.maf.tsv`

Lollipop plots: 
`atrx-lollipop-all.pdf`
`atrx-lollipop-alt-neg.tiff`
`atrx-lollipop-alt-pos.tiff`
`atrx-lollipop-comp.tiff`
`atrx-lollipop-oncogenic.pdf`
`atrx-lollipop-vus.pdf`

#### What is your summary of the results?

The `atria-lollipop-comp.tiff` plot now includes one additional sample in the ALT- group (N=47 vs N=46 previously). 

#### Documentation Checklist

- [X] This analysis module has a `README` and it is up to date.
- [X] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by jharenza** [comment]
Script 01 runs fine for me, but I am getting an error with script 2:
```
Traceback (most recent call last):
  File "/home/oncokb-annotator/MafAnnotator.py", line 7, in <module>
    from AnnotatorCore import setsampleidsfileterfile
  File "/home/oncokb-annotator/AnnotatorCore.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

My token is still valid, so I am not sure if I don't fully have the oncokb annotator fully installed in the docker image somehow. Assuming this worked fine for you in docker?

**Comment by rjcorb** [comment]
I just checked and there are [two dependencies not installed in the docker image](https://github.com/oncokb/oncokb-annotator/blob/master/requirements/common.txt). I believe I installed them while in the docker container, hence why it isn't reproducible currently.

**Comment by jharenza** [comment]
Perfect, thanks - will update the dockerfile in a separate PR - I just looked over there and missed the "common" ones when checking!

**Review by jharenza — APPROVED** [review]
With the new dockerfile changes in #63, this runs as expected. I checked the lollipops (we are using ALT + and ALT - in the manuscript) and those are identical. The oncokb mafs are also unchanged, so to wrap this up, I think you can remove the commented params in 03 and we can merge. Approving so you can merge once done. Thanks for doing this!

**Pull request merged**
